<?php
$typeArr[1] = '学院概况';
$typeArr[2] = '招生计划';
$typeArr[3] = '招生政策';
$typeArr[4] = '报考指南';
$typeArr[5] = '招聘信息';
$typeArr[7] = '新闻中心';
$typeArr[8] = '通知通告';
$typeArr[9] = '热点问题';
$typeArr[23] = '教育信息';
$typeArr[24] = '人才培养';
$typeArr[10] = '合作交流';
$typeArr[11] = '校园风光';
$typeArr[28] = '学科科研';
$typeArr[13] = '首页幻灯片';
$typeArr[17] = '学院动态';
$typeArr[18] = '院系新闻';
$typeArr[19] = '合作发展';
$typeArr[14] = '院系设置';
$typeArr[27] = '学院发展';
$typeArr[15] = '在线咨询';
$typeArr[16] = '录取查询';
$typeArr[20] = '国际合作';
$typeArr[29] = '学术期刊';
?>