{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/160830/1-160S0215033.jpg' text='' width='260' height='195'} /uploads/allimg/160830/1-160S0215033.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/160830/1-160S0215034.jpg' text='' width='260' height='195'} /uploads/allimg/160830/1-160S0215034.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/160830/1-160S0215035.jpg' text='' width='260' height='195'} /uploads/allimg/160830/1-160S0215035.jpg {/dede:img}
