<li><img src="[field:litpic/]" alt="[field:title/]" />
          <div class="overlay hidden-l">
            <div class="container">
              <div class="x10 x1-move text-center slider-text">
                <div class="slider-text-inner">
                  <h2>[field:title/]</h2>
                  <p class="f-txt">[field:description function="cn_substr(@me,188)"/]......</p>
                  <p class="f-btn"><a href="/" >查看详情&nbsp;<span class="icon-arrow-circle-o-right"></span></a></p>
                </div>
              </div>
            </div>
          </div>
        </li>