<?php
$z[0]=Array("arcurl","",153,168);
$z[1]=Array("litpic","",195,210);
$z[2]=Array("litpic","",228,243);
$z[3]=Array("title","",250,264);
$z[4]=Array("arcurl","",347,362);
$z[5]=Array("title","",371,385);
$z[6]=Array("title","",387,401);
$z[7]=Array("pubdate","",446,493);
$z[7][4]['function']="MyDate('Y/m/d',@me)";
$z[8]=Array("description","",533,583);
$z[8][4]['function']="cn_substr(@me,255)";
$z[9]=Array("arcurl","",595,610);

?>