{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/160830/1-160S0215134.jpg' text='' width='260' height='195'} /uploads/allimg/160830/1-160S0215134.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/160830/1-160S0215135.jpg' text='' width='260' height='195'} /uploads/allimg/160830/1-160S0215135.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/160830/1-160S0215136.jpg' text='' width='260' height='195'} /uploads/allimg/160830/1-160S0215136.jpg {/dede:img}
