<?php
$z[0]=Array("arcurl","",153,168);
$z[1]=Array("ltpic","",195,209);
$z[2]=Array("ltpic","",227,241);
$z[3]=Array("title","",248,262);
$z[4]=Array("arcurl","",345,360);
$z[5]=Array("title","",369,383);
$z[6]=Array("title","",385,399);
$z[7]=Array("pubdate","",444,491);
$z[7][4]['function']="MyDate('Y/m/d',@me)";
$z[8]=Array("description","",531,581);
$z[8][4]['function']="cn_substr(@me,180)";
$z[9]=Array("arcurl","",593,608);

?>