<div class="xm4 xb4 xs6 xl6 not-animated"  data-animate="slideInUp">
            <div class="pro-item">
              <div class="portfolio-img"><a href="[field:arcurl/]" title="[field:title/]"><img class="lazy"  src="/skin/img/grey.gif"  data-original="[field:litpic/]" alt="[field:title/]"/></a></div>
              <h2><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h2>
            </div>
          </div>