<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/160830/1-160S0214S3.jpg ",93,236);
$z[1][4]['ddimg']="/uploads/allimg/160830/1-160S0214S3.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="260";
$z[1][4]['height']="195";
$z[2]=Array("img"," /uploads/allimg/160830/1-160S0214S4.jpg ",238,381);
$z[2][4]['ddimg']="/uploads/allimg/160830/1-160S0214S4.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="260";
$z[2][4]['height']="195";
$z[3]=Array("img"," /uploads/allimg/160830/1-160S0214S5.jpg ",383,526);
$z[3][4]['ddimg']="/uploads/allimg/160830/1-160S0214S5.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="260";
$z[3][4]['height']="195";
$z[4]=Array("img"," /uploads/allimg/160830/1-160S0214S6.jpg ",528,671);
$z[4][4]['ddimg']="/uploads/allimg/160830/1-160S0214S6.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="260";
$z[4][4]['height']="195";
$z[5]=Array("img"," /uploads/allimg/160830/1-160S0214S7.jpg ",673,816);
$z[5][4]['ddimg']="/uploads/allimg/160830/1-160S0214S7.jpg";
$z[5][4]['text']="";
$z[5][4]['width']="260";
$z[5][4]['height']="195";

?>