<div class="xl12 xs6 xm6  item-block">
          <div class="item"><span class="spanicon spanicon1"></span><span class="spanicon spanicon2"></span><span class="spanicon spanicon4"></span><span class="spanicon spanicon3"></span>
            <div class="media media-x">
              <div class="media-img float-left">
                <div class="imgs"><a class="himg" href="/a/kehufuwu/changjianwenti/" target="_blank"><img class="lazy"  src="/skin/img/grey.gif"  data-original="/skin/img/2017318162050818.png" alt="常见问题"  /></a>
                  <div class="overlay"><a class="cimg" href="/a/kehufuwu/changjianwenti/" title="常见问题" target="_blank"><img class="lazy"  src="/skin/img/grey.gif"  data-original="/skin/img/2017318162055885.png" alt="常见问题"  /></a></div>
                </div>
              </div>
              <div class="media-body">
                <h4><a href="/a/kehufuwu/changjianwenti/" target="_blank">常见问题</a></h4>
                <p class="desc">问题现象：电水壶不能工作、指示灯不亮故障原因：1-插电</p>
                <p class="more"><a href="/a/kehufuwu/changjianwenti/" target="_blank">查看更多<span class="icon-long-arrow-right"></span></a></p>
              </div>
            </div>
          </div>
        </div>