<div class="xl12 xs6 xm6  item-block">
          <div class="item"><span class="spanicon spanicon1"></span><span class="spanicon spanicon2"></span><span class="spanicon spanicon4"></span><span class="spanicon spanicon3"></span>
            <div class="media media-x">
              <div class="media-img float-left">
                <div class="imgs"><a class="himg" href="/a/kehufuwu/jishuzhichi/" target="_blank"><img class="lazy"  src="/skin/img/grey.gif"  data-original="/skin/img/2017318161927514.png" alt="[field:typename /]"  /></a>
                  <div class="overlay"><a class="cimg" href="/a/kehufuwu/jishuzhichi/" title="[field:typename /]" target="_blank"><img class="lazy"  src="/skin/img/grey.gif"  data-original="/skin/img/2017318161931934.png" alt="[field:typename /]"  /></a></div>
                </div>
              </div>
              <div class="media-body">
                <h4><a href="/a/kehufuwu/jishuzhichi/" target="_blank">[field:typename /]</a></h4>
                <p class="desc">[field:description /]</p>
                <p class="more"><a href="/a/kehufuwu/jishuzhichi/" target="_blank">查看更多<span class="icon-long-arrow-right"></span></a></p>
              </div>
            </div>
          </div>
        </div>