






<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:tel itemname="手机号" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:tel>


<field:email itemname="邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:email>









<field:add itemname="详细地址" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:add>

<field:content itemname="信息描述" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:content>
