<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/160830/1-160S0214Z8.jpg ",93,236);
$z[1][4]['ddimg']="/uploads/allimg/160830/1-160S0214Z8.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="260";
$z[1][4]['height']="195";
$z[2]=Array("img"," /uploads/allimg/160830/1-160S0214911.jpg ",238,383);
$z[2][4]['ddimg']="/uploads/allimg/160830/1-160S0214911.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="260";
$z[2][4]['height']="195";
$z[3]=Array("img"," /uploads/allimg/160830/1-160S0214912.jpg ",385,530);
$z[3][4]['ddimg']="/uploads/allimg/160830/1-160S0214912.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="260";
$z[3][4]['height']="195";
$z[4]=Array("img"," /uploads/allimg/160830/1-160S0214914.jpg ",532,677);
$z[4][4]['ddimg']="/uploads/allimg/160830/1-160S0214914.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="260";
$z[4][4]['height']="195";
$z[5]=Array("img"," /uploads/allimg/160830/1-160S0214915.jpg ",679,824);
$z[5][4]['ddimg']="/uploads/allimg/160830/1-160S0214915.jpg";
$z[5][4]['text']="";
$z[5][4]['width']="260";
$z[5][4]['height']="195";

?>