<div class="xl12 xs6 xm6  item-block">
          <div class="item"><span class="spanicon spanicon1"></span><span class="spanicon spanicon2"></span><span class="spanicon spanicon4"></span><span class="spanicon spanicon3"></span>
            <div class="media media-x">
              <div class="media-img float-left">
                <div class="imgs"><a class="himg" href="/a/kehufuwu/baoxiutiaoli/" target="_blank"><img class="lazy"  src="/skin/img/grey.gif"  data-original="/skin/img/2017318162211515.png" alt="保修条例"  /></a>
                  <div class="overlay"><a class="cimg" href="/a/kehufuwu/baoxiutiaoli/" title="保修条例" target="_blank"><img class="lazy"  src="/skin/img/grey.gif"  data-original="/skin/img/2017318162319580.png" alt="保修条例"  /></a></div>
                </div>
              </div>
              <div class="media-body">
                <h4><a href="/a/kehufuwu/baoxiutiaoli/" target="_blank">保修条例</a></h4>
                <p class="desc">本品牌全线产品，在设计、制做方面都按高端产品质量定位</p>
                <p class="more"><a href="/a/kehufuwu/baoxiutiaoli/" target="_blank">查看更多<span class="icon-long-arrow-right"></span></a></p>
              </div>
            </div>
          </div>
        </div>