<li class="widget ">
          <div class="cover overlay overlay-hover"> <img class="cover-image overlay-scale" src="[field:litpic/]" alt="[field:title/]" style='height:300px;'/>
            <div class="overlay-panel overlay-fade overlay-background overlay-background-fixed text-center vertical-align">
              <div class="vertical-align-middle">
                <div class="widget-time widget-divider"> <span>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span> </div>
                <h3 class="widget-title margin-bottom-20">[field:title/]</h3>
                <button type="button" class="btn btn-outline btn-squared btn-inverse met-img-showbtn">
                <a href="[field:arcurl/]">浏览</a>
                </button>
              </div>
            </div>
          </div>
        </li>