<div class="xm4 xb4 xs6 xl6">
                    <div class="item">
                      <div class="pro-item">
                        <div class="portfolio-img"><a href="[field:arcurl/]" title="[field:title/]"><img src="[field:litpic/]" alt="[field:title/]" /></a></div>
                        <h2><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h2>
                      </div>
                    </div>
                  </div>