
<field:xm itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:xm>

<field:dh itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dh>

<field:yx itemname="Email" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:yx>

<field:qt itemname="省份" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:qt>

<field:nr itemname="留言内容" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:nr>



<field:times itemname="发布时间" autofield="1" type="datetime" isnull="true" default=""  maxlength="250" page="">
</field:times>

<field:hf itemname="管理员回复" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:hf>
