<?php
$z[0]=Array("field","",378,397);
$z[0][4]['name']="title";
$z[1]=Array("global","",398,424);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",465,494);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",534,592);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1583,1618);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n<li class=\"\"><a href=\"[field:typelink/]\" target=\"\">[field:typename/]</a></li>\r\n",1944,2156);
$z[5][4]['type']="son";
$z[5][4]['currentstyle']="<li class='active'><a href='~typelink~' >~typename~</a> </li>";
$z[6]=Array("field","",2294,2323);
$z[6][4]['name']="position";
$z[7]=Array("field","",2635,2655);
$z[7][4]['name']="litpic";
$z[8]=Array("field","",2664,2683);
$z[8][4]['name']="title";
$z[9]=Array("field","",2731,2751);
$z[9][4]['name']="litpic";
$z[10]=Array("field","",2840,2859);
$z[10][4]['name']="title";
$z[11]=Array("field","",2898,2923);
$z[11][4]['name']="description";
$z[12]=Array("field","",7703,7721);
$z[12][4]['name']="body";
$z[13]=Array("prenext","",7835,7860);
$z[13][4]['get']="pre";
$z[14]=Array("prenext","",7880,7906);
$z[14][4]['get']="next";
$z[15]=Array("include","",7980,8017);
$z[15][4]['filename']="footer.htm";

?>