<li class="list-group-item">
                <div class="media">
                  <div class="media-left"> <i class="icon wb-user-circle" aria-hidden="true"></i> </div>
                  <div class="media-body">
                    <h4 class="media-heading"> <small class="pull-right">  {dede:php runphp='yes'}
$ntime = time();
 @me=MyDate('Y年m月d日 h时m分s秒',$ntime);
 {/dede:php}</small> [field:xm/] </h4>
                    <p>[field:content/]</p>
                    <div class="content well margin-bottom-0"> [field:hf/] </div>
                  </div>
                </div>
              </li>