<div class="xl6 xs3 xm3  text-center item-block">
        <div class="item not-animated"  data-animate="fadeInDown" data-delay="200">
          <div class="imgs"><a class="himg" href="[field:typeurl /]" title="[field:typename /]" target="_blank"><img class="lazy"  src="/skin/img/grey.gif"  data-original="/skin/img/2017317142721100.png" alt="[field:typename /]"  />
            <p>[field:typename /]</p>
            </a>
            <div class="overlay"><a class="cimg" href="[field:typeurl /]" title="[field:typename /]" target="_blank"><img class="lazy"  src="/skin/img/grey.gif"  data-original="/skin/img/2017317142725308.png" alt="[field:typename /]"  />
              <p>[field:typename /]</p>
              </a></div>
          </div>
        </div>
      </div>