<li>
              <h4> <a href="[field:arcurl/]" title="[field:title/]"> [field:title/] </a> </h4>
              <p class="des">[field:description function="cn_substr(@me,255)"/]...</p>
              <p class="info"> <span>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span> <span>admin</span> <span><i class="icon wb-eye margin-right-5" aria-hidden="true"></i>[field:click/]</span> </p>
            </li>