<li class=" not-animated"  data-animate="slideInUp">
            <div class="media media-x">
              <div class="media_img float-left"><a  href="[field:arcurl/]" ><img class="lazy"  src="[field:litpic/]"  data-original='[field:litpic/]' alt='[field:title/]'></a></div>
              <div class="media-body">
                <h3><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h3>
                <div class='time'>[field:pubdate function="MyDate('Y/m/d',@me)"/]</div>
                <p class="desc">[field:description function="cn_substr(@me,180)"/]...<a href='[field:arcurl/]'  target="_blank">...More&gt;&gt;</a></p>
              </div>
            </div>
          </li>