<div class="xl12 xs6 xm6  item-block">
          <div class="item"><span class="spanicon spanicon1"></span><span class="spanicon spanicon2"></span><span class="spanicon spanicon4"></span><span class="spanicon spanicon3"></span>
            <div class="media media-x">
              <div class="media-img float-left">
                <div class="imgs"><a class="himg" href="/a/kehufuwu/weixiuwangdian/" target="_blank"><img class="lazy"  src="/skin/img/grey.gif"  data-original="/skin/img/201731816240831.png" alt="维修网点"  /></a>
                  <div class="overlay"><a class="cimg" href="/a/kehufuwu/weixiuwangdian/" title="维修网点" target="_blank"><img class="lazy"  src="/skin/img/grey.gif"  data-original="/skin/img/201731816249706.png" alt="维修网点"  /></a></div>
                </div>
              </div>
              <div class="media-body">
                <h4><a href="/a/kehufuwu/weixiuwangdian/" target="_blank">维修网点</a></h4>
                <p class="desc">维修，快速维修，快捷服务维修力洋维修，快捷服务维修</p>
                <p class="more"><a href="/a/kehufuwu/weixiuwangdian/" target="_blank">查看更多<span class="icon-long-arrow-right"></span></a></p>
              </div>
            </div>
          </div>
        </div>