<li class="list-group-item">
                <div class="media">
                  <div class="media-left"> <i class="icon wb-user-circle" aria-hidden="true"></i> </div>
                  <div class="media-body">
                    <h4 class="media-heading"> <small class="pull-right"> </small> [field:xm/] </h4>
                    <p>[field:content/]</p>
                    <div class="content well margin-bottom-0"> [field:hf/] </div>
                  </div>
                </div>
              </li>