<?php
$z[0]=Array("channelartlist","\r\n        <div class=\"col-md-2 col-sm-2 col-xs-6 list masonry-item\">\r\n          <h4><a href=\"{dede:field name='typeurl'/}\"  title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}</a></h4>\r\n        </div>\r\n		",167,470);
$z[0][4]['typeid']="top";
$z[0][4]['row']="6";
$z[0][4]['currentstyle']="cur";
$z[1]=Array("global","",849,875);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",1091,1113);
$z[2][4]['name']="cfg_tel";

?>