<?php
$z[0]=Array("global","",348,370);
$z[0][4]['name']="cfg_add";
$z[1]=Array("global","",402,426);
$z[1][4]['name']="cfg_email";
$z[2]=Array("global","",458,480);
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",501,524);
$z[3][4]['name']="cfg_tels";
$z[4]=Array("channelartlist","<div class=\"x6 item\"><a href='{dede:field name='typeurl'/}'><&nbsp;{dede:field name='typename'/}</a></div>",768,957);
$z[4][4]['typeid']="top";
$z[4][4]['row']="5";
$z[4][4]['currentstyle']="cur";
$z[5]=Array("global","",2047,2068);
$z[5][4]['name']="cfg_qq";
$z[6]=Array("flink","  [field:link /] | ",2645,2724);
$z[6][4]['titlelen']="20";
$z[6][4]['row']="20";
$z[6][4]['type']="text";
$z[7]=Array("global","",2863,2889);
$z[7][4]['name']="cfg_powerby";
$z[8]=Array("global","",3254,3276);
$z[8][4]['name']="cfg_tel";
$z[9]=Array("global","",3359,3382);
$z[9][4]['name']="cfg_tels";

?>