<?php
$z[0]=Array("global","",893,919);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",946,972);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",1058,1084);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",1093,1119);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("global","",2511,2537);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("global","",2660,2686);
$z[5][4]['name']="cfg_webname";
$z[6]=Array("global","",2695,2721);
$z[6][4]['name']="cfg_webname";
$z[7]=Array("channelartlist","\r\n        <li class=\"dropdown margin-left-0\"> <a data-toggle=\"dropdown\" data-hover=\"dropdown\" aria-expanded=\"false\" class=\"dropdown-toggle link\" href=\"{dede:field name='typeurl'/}\" class=\"link\">{dede:field name='typename'/}<i class=\"fa fa-caret-down\"></i> </a>\r\n          <ul class=\"dropdown-menu dropdown-menu-right maxNavlist\">\r\n            {dede:channel type='son' noself='yes'}\r\n            <li><a href=\"[field:typelink/]\" class=\" nav2list\"  title=\"[field:typename/]\">[field:typename/]</a></li>\r\n			{/dede:channel}\r\n          </ul>\r\n        </li>\r\n		",2837,3470);
$z[7][4]['typeid']="top";
$z[7][4]['currentstyle']="current";

?>