<?php
$z[0]=Array("field","",353,372);
$z[0][4]['name']="title";
$z[1]=Array("global","",373,399);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",440,469);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",509,567);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",642,677);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n          <li><a href=\"[field:typelink/]\"  title=\"[field:typename/]\" class=\"link\">[field:typename/]</a> </li>\r\n",1150,1408);
$z[5][4]['type']="son";
$z[5][4]['currentstyle']="<li><a href='~typelink~' class='link active'>~typename~</a> </li>";
$z[6]=Array("loop","\r\n              <li class=\"list-group-item\">\r\n                <div class=\"media\">\r\n                  <div class=\"media-left\"> <i class=\"icon wb-user-circle\" aria-hidden=\"true\"></i> </div>\r\n                  <div class=\"media-body\">\r\n                    <h4 class=\"media-heading\"> <small class=\"pull-right\"> </small> [field:xm/] </h4>\r\n                    <p>[field:content/]</p>\r\n                    <div class=\"content well margin-bottom-0\"> [field:hf/] </div>\r\n                  </div>\r\n                </div>\r\n              </li>\r\n			   ",1751,2370);
$z[6][4]['table']="dede_diyform2";
$z[6][4]['sort']="id";
$z[6][4]['row']="30";
$z[6][4]['if']="ifcheck=1";
$z[7]=Array("include","",5912,5950);
$z[7][4]['filename']="footnav.htm";
$z[8]=Array("include","",5952,5989);
$z[8][4]['filename']="footer.htm";

?>