<?php
$z[0]=Array("field","",353,372);
$z[0][4]['name']="title";
$z[1]=Array("global","",373,399);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",440,469);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",509,567);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",642,677);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n          <li><a href=\"[field:typelink/]\"  title=\"[field:typename/]\" class=\"link\">[field:typename/]</a> </li>\r\n",1150,1408);
$z[5][4]['type']="son";
$z[5][4]['currentstyle']="<li><a href='~typelink~' class='link active'>~typename~</a> </li>";
$z[6]=Array("include","",4955,4993);
$z[6][4]['filename']="footnav.htm";
$z[7]=Array("include","",4995,5032);
$z[7][4]['filename']="footer.htm";

?>