<?php
$z[0]=Array("field","",378,397);
$z[0][4]['name']="title";
$z[1]=Array("global","",398,424);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",465,494);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",534,592);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1103,1138);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n<li class=\"\"><a href=\"[field:typelink/]\" target=\"\">[field:typename/]</a></li>\r\n",1463,1675);
$z[5][4]['type']="son";
$z[5][4]['currentstyle']="<li class='active'><a href='~typelink~' >~typename~</a> </li>";
$z[6]=Array("field","",1813,1842);
$z[6][4]['name']="position";
$z[7]=Array("include","",4290,4327);
$z[7][4]['filename']="footer.htm";

?>