<?php
$z[0]=Array("field","",379,398);
$z[0][4]['name']="title";
$z[1]=Array("global","",399,425);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",466,495);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",535,593);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1104,1139);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n<li class=\"\"><a href=\"[field:typelink/]\" target=\"\">[field:typename/]</a></li>\r\n",1464,1676);
$z[5][4]['type']="son";
$z[5][4]['currentstyle']="<li class='active'><a href='~typelink~' >~typename~</a> </li>";
$z[6]=Array("field","",1814,1843);
$z[6][4]['name']="position";
$z[7]=Array("include","",4291,4328);
$z[7][4]['filename']="footer.htm";

?>