<?php
$z[0]=Array("field","",352,371);
$z[0][4]['name']="title";
$z[1]=Array("global","",372,398);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",439,468);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",508,566);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",641,676);
$z[4][4]['filename']="head.htm";
$z[5]=Array("list","\r\n        <li class=\"widget \">\r\n          <div class=\"cover overlay overlay-hover\"> <img class=\"cover-image overlay-scale\" src=\"[field:litpic/]\" alt=\"[field:title/]\" style='height:300px;'/>\r\n            <div class=\"overlay-panel overlay-fade overlay-background overlay-background-fixed text-center vertical-align\">\r\n              <div class=\"vertical-align-middle\">\r\n                <div class=\"widget-time widget-divider\"> <span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span> </div>\r\n                <h3 class=\"widget-title margin-bottom-20\">[field:title/]</h3>\r\n                <button type=\"button\" class=\"btn btn-outline btn-squared btn-inverse met-img-showbtn\">\r\n                <a href=\"[field:arcurl/]\">浏览</a>\r\n                </button>\r\n              </div>\r\n            </div>\r\n          </div>\r\n        </li>\r\n		",1164,2035);
$z[5][4]['pagesize']="8";
$z[6]=Array("pagelist","",2095,2160);
$z[6][4]['listitem']="index,end,pre,next,pageno";
$z[6][4]['listsize']="5";
$z[7]=Array("include","",2240,2278);
$z[7][4]['filename']="footnav.htm";
$z[8]=Array("include","",2280,2317);
$z[8][4]['filename']="footer.htm";

?>