<?php
$z[0]=Array("field","",378,397);
$z[0][4]['name']="title";
$z[1]=Array("global","",398,424);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",465,494);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",534,592);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1103,1138);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n<li class=\"\"><a href=\"[field:typelink/]\" target=\"\">[field:typename/]</a></li>\r\n",1464,1676);
$z[5][4]['type']="son";
$z[5][4]['currentstyle']="<li class='active'><a href='~typelink~' >~typename~</a> </li>";
$z[6]=Array("field","",1814,1843);
$z[6][4]['name']="position";
$z[7]=Array("list","\r\n		<div class=\"xm4 xb4 xs6 xl6 not-animated\"  data-animate=\"slideInUp\">\r\n            <div class=\"pro-item\">\r\n              <div class=\"portfolio-img\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img class=\"lazy\"  src=\"/skin/img/grey.gif\"  data-original=\"[field:litpic/]\" alt=\"[field:title/]\"/></a></div>\r\n              <h2><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></h2>\r\n            </div>\r\n          </div>\r\n		  ",2075,2557);
$z[7][4]['pagesize']="6";
$z[8]=Array("pagelist","",2691,2756);
$z[8][4]['listitem']="index,end,pre,next,pageno";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",2839,2876);
$z[9][4]['filename']="footer.htm";

?>